baseurl = "https://neuromaternal.github.io/"
title = "NeuroMaternal"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "My blog"
    weight = 1
    contentDir = "content/en"
  [languages.fr]
    title = "Mon blogue"
    weight = 2
    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "cosas de neuroimagen y madre. A veces padres, maybe"
  facebook = ""
  twitter = ""
  instagram = "https://www.instagram.com/neuro.maternal/?hl=es"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/imagen_alberto.jpeg"
  recent_posts_number = 2
